#!/usr/bin/env python
from docopt import docopt
from socketserver import ForkingTCPServer
from vampires_control.server import DEFAULT_HOST, DEFAULT_PORT, VAMPIRESHandler

__doc__ = f"""
Usage:
    vampiresd [-h | --help] [--host <HOST>] [-p <PORT> | --port <PORT>]

Launch the VAMPIRES server daemon.

Options:
    -h --help           Print this message
    --host <HOST>       Change the port, default is {DEFAULT_HOST}
    -p --port <PORT>    Change the port, default is {DEFAULT_PORT}

"""

if __name__ == "__main__":
    args = docopt(__doc__)
    port = args["--port"] if args["--port"] is not None else DEFAULT_PORT
    host = args["--host"] if args["--host"] is not None else DEFAULT_HOST

    print(f"launching server on at {host}:{port}")

    with ForkingTCPServer((host, port), VAMPIRESHandler) as server:
        server.serve_forever()
