#!/usr/bin/env python
from docopt import docopt
import socket

from vampires_control.server import DEFAULT_HOST, DEFAULT_PORT


def send_command(string, host, port, response=False):
    pass


__doc__ = f"""
Usage:
    vampires [-h | --help] [--host <HOST>] [-p <PORT> | --port <PORT>] [-w | --wait] <command> [<args> ...]

Interface with the VAMPIRES instrument control daemon from the command line. 

Options:
    -h --help           Print this message
    --host <HOST>       VAMPIRES daemon host, default is {DEFAULT_HOST}
    -p --port <PORT>    VAMPIRES daemon port, default is {DEFAULT_PORT}
    -w --wait           For commands which move stages, will block until movement is completed

Commands:
    (g)et <KEYWORD>   Query a keyword from the VAMPIRES status

"""

if __name__ == "__main__":
    args = docopt(__doc__)
    host = args["--host"] if args["--host"] is not None else DEFAULT_HOST
    port = int(args["--port"]) if args["--port"] is not None else DEFAULT_PORT

    _args = " ".join(args["<args>"])
    if args["--wait"]:
        _args += " --wait"
    cmd = f"{args['<command>']} {_args}"
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.connect((host, port))
        sock.sendall(bytes(cmd, "ascii"))
        resp = str(sock.recv(1024), "ascii")
        if resp:
            print(resp)
