#!/usr/bin/env python
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from pathlib import Path
from subprocess import run
import sys
import logging
import time
from logging.handlers import SysLogHandler

from vampires_control.devices import differential_filter 
from vampires_control.state import VAMPIRES

formatter = "%(asctime)s|%(levelname)s|%(name)s - %(message)s"
logging.basicConfig(
    level=logging.DEBUG, format=formatter, handlers=[logging.StreamHandler()]
)
logger = logging.getLogger("vampires_diffwheel")

# step 1. parse the input file
CONF_FILE = "/etc/vampires-control/conf_vampires_diffwheel.txt"
logger.debug(f"using configuration file '{CONF_FILE}'")

with open(CONF_FILE) as fh:
    lines = fh.readlines()

logger.debug(f"read {len(lines)} lines")

positions = [l.split(";")[0] for l in lines]
cam1 = [l.split(";")[1].strip() for l in lines]
cam2 = [l.split(";")[2].strip() for l in lines]
descriptions = [f"{d1} / {d2}" for d1, d2 in zip(cam1, cam2)]
angles = [float(l.split(";")[3].strip()) for l in lines]

epilog = "positions (cam1 / cam2):\n"
epilog += "\n".join([f"  {i} {d}" for i, d in zip(positions, descriptions)])

# step 2. define functions for argparse




def move(args):
    idx = int(args.position) - 1
    angle = angles[idx]
    differential_filter.move_absolute(angle, wait=args.wait)
    VAMPIRES["differential_filter_wheel"] = args.position


# def wheel(args):
#     if args.command == "status":
#         cmd = f"conex 9 TP"
#         print("DEBUG: command sent: ", cmd)
#     elif args.command == "home":
#         cmd = f"conex 9 OR"
#         print("DEBUG: command sent: ", cmd)
#     elif args.command == "goto":
#         angle = args.args[0]
#         cmd = f"conex 9 PA {args.angle}"
#         print("DEBUG: command sent: ", cmd)

# step 3. create argument parser
parser = ArgumentParser(
    description="Switch the VAMPIRES differential filter wheel optics",
    epilog=epilog,
    formatter_class=RawDescriptionHelpFormatter,
)
parser.add_argument(
    "position", choices=positions, nargs="?", help="move to the position"
)
parser.add_argument(
    "-w", "--wait", action="store_true", help="block until movement is finished, if applicable"
)
parser.set_defaults(func=move)

# subparsers = parser.add_subparsers(title="wheel commands")

# wheel_parser = subparsers.add_parser("wheel")
# wheel_parser.add_argument("command", choices=["status", "home", "goto"])
# wheel_parser.add_argument("args", nargs="*")


# setp 4. action
if __name__ == "__main__":
    if len(sys.argv) == 1:
        parser.print_help()
    else:
        args = parser.parse_args()
        args.func(args)
